plugins {
    id 'peacefulaura.loader'
    id 'net.fabricmc.fabric-loom'
}

loom {
    runs {
        client {
            client()
            getDisplayName().set 'Fabric - Client'
            getGenerateRunConfig().set true
            getRunDirectory().set file('runs/client')
        }

        server {
            server()
            getDisplayName().set 'Fabric - Server'
            getGenerateRunConfig().set true
            getRunDirectory().set file('runs/server')
        }
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

def replaceProperties = sharedModMetadata + [
        fabric_loader_version: fabric_loader_version
]

tasks.named('processResources', ProcessResources) {
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}