org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.0.1
minecraft_version=26.2
java_version=25

neo_form_version=26.2-2
moddevgradle_version=2.0.144

mod_id=peacefulaura
maven_group=org.emrila.peacefulaura

mod_name=Peaceful Aura
mod_license=MIT
mod_authors=Emrila
mod_description=Adds an effect (edible and potion) that temporarily prevents mobs from targeting and attacking.

curseforge_url=https://www.curseforge.com/minecraft/mc-mods/peaceful-aura
sources_url=https://github.com/emrila/PeacefulAura
issue_tracker_url=https://github.com/emrila/PeacefulAura/issues

# Fabric Properties
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.156.0+26.2
