# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true

# Project
mod_version=1.0.1
maven_group=org.emrila.peacefulaura
minecraft_version=26.2
java_version=25

# Mod
mod_id=peacefulaura
mod_name=Peaceful Aura
mod_license=MIT
mod_authors=Emrila
mod_description=Adds an effect (edible and potion) that temporarily prevents mobs from targeting and attacking.

curseforge_url=https://www.curseforge.com/minecraft/mc-mods/peaceful-aura
sources_url=https://github.com/emrila/PeacefulAura
issue_tracker_url=https://github.com/emrila/PeacefulAura/issues

# Common
neo_form_version=26.2-2

# Fabric
loom_version=1.17-SNAPSHOT
fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2

# NeoForge
moddevgradle_version=2.0.144
neoforge_version=26.2.0.59
neoforge_version_range=[26,)
neoforge_loader_version_range=[4,)
minecraft_version_range=[26.2]